version: '2'
services:
    web:
        image: mfay/anotherexpress:1.0
        restart: always
        ports:
            - "80:3000"
        links:
            - redis
            - mongo
        depends_on:
            - redis
            - mongo
    mongo:
        image: mongo
        restart: always
    redis: 
        image: redis:3.2
        restart: always
